[package]
name = "oxido"
version = "2.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
codespan-reporting = "0.11.1"